- name: Remove "certbot" package
  apt:
    name: certbot
    state: absent

- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Update snapd
  command: snap install core

- name: Refresh snapd
  command: snap refresh core

- name: Install certbot snap
  command: snap install --classic certbot

- name: Create a symbolic link to certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
