---
- name: "Add the official OpenVPN APT key; hiding 25 lines of log..."
  apt_key:
    id: 30EBF4E73CCE63EEE124DD278E6DA8B4E158C569
    data: "{{ item }}"
  with_file: openvpn_signing.key
  no_log: True

- name: Add the official OpenVPN repository
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.4 stretch main
    repo_key: 30EBF4E73CCE63EEE124DD278E6DA8B4E158C569

- name: Install OpenVPN and its dependencies from APT
  apt:
    package:
      - openvpn
      - udev
