---
- name: Install service0 network configuration
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/network/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-service0.netdev
    - 10-service0.network

- name: Enable and start systemd networking
  systemd:
    daemon_reload: yes
    name: systemd-networkd.service
    enabled: yes
    state: restarted

- name: Install dnsmasq for service0 network
  copy:
    src: service-net.conf
    dest: /etc/dnsmasq.d/
    owner: root
    group: root
    mode: 0644

- name: "sudo systemctl disable systemd-resolved"
  command: "sudo systemctl disable systemd-resolved"
  become: yes

- name: "sudo systemctl stop systemd-resolved"
  command: "sudo systemctl stop systemd-resolved"
  become: yes

- name: "Restart DNSMasq to pick up the new configuration"
  service:
    name: dnsmasq
    state: restarted
